### ISSUE TITLE
Invoke-TmfAccessPackageResource errors when adding an App Resource 

### ISSUE THREAD

**Issue by verasbr** [ATVWGS/tenant-management-framework#14] opened 2022-08-24 08:13 UTC
![image](https://user-images.githubusercontent.com/48932313/186365688-3cb22fc4-5b1c-4742-ae36-4d6560f7b0c7.png)
Getting the above error when using TMF to adding an App Resource to an access package. Running Test-TMFTenant shows the App Resource  will be created

**Comment by verasbr** [comment] 2022-08-25 03:52
Notice your using _Invoke-MgGraphRequestMethod_ for this and that there is now a cmdlet for this  [type of request](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&tabs=powershell#request-5). This might have something to do with it?

**Comment by jbmartin90** [comment] 2022-08-26 06:33
I noticed when running TMF locally to troubleshoot that "resourceType" for apps was defaulting to "AadGroup", so in the json file I added "resourceType":"Application". This resulted in a new error about "originId".
![image](https://user-images.githubusercontent.com/93702948/186837046-0b4504b3-935f-4777-a360-05b52198644a.png)

I then defined "originID" in the json but still got the same error. Seems like an issue with looking up application resource attributes when building the payload for Graph.
![image](https://user-images.githubusercontent.com/93702948/186837606-0689d7e6-603a-4424-ae25-4abcc98579e5.png)

**Comment by brine0m** [comment] 2022-08-26 08:54
The issue appears to with this part of the code

https://github.com/ATVWGS/tenant-management-framework/blob/1b3c643ccaf8fa98a712fa8b366db972e5974557/TMF/functions/entitlementManagement/accessPackageResource/Register-TmfAccessPackageResource.ps1#L65

The switch only has AadGroup or DEFAULT to set the origin ID. In the above it would be using the deault

A work around for the issue is to add a parameter of "resourceIdentifier" and set the value to ObjectID of the application

**Comment by ATVWGS** [comment] 2022-09-07 09:40
We've created an internal bug for this.

**Comment by brine0m** [comment] 2022-09-27 02:25
@ATVWGS , are there any updates to resolving this? Any chance an updated build will be coming out soon?

**Comment by ATVWGS** [comment] 2022-09-28 14:06
Hi @brine0m,

I've just released a preview version that is working with applications in accessPackages. A lookup of valid roles within the Register function can not work, because a new accessPackageResource is not yet deployed during the Register flow and therefore roles of the application cannot be gathered. The validation set was completly removed.
Here is an example how accessPackagesResources could look like:

"accessPackageResources": [
{
"originSystem": "AadApplication",
"resourceRole": "Default Access",
"resourceType": "Application",
"resourceIdentifier": "Graph Explorer"
},
{
"originSystem": "AadGroup",
"resourceRole": "Member",
"resourceIdentifier": "Some group name"
}
]

Note: The "resourceRole" attribute of the application can only be the displayname of the role.

**Closed by ATVWGS** 2022-09-28 14:06 UTC
